package com.nextel.bean;


/**
 * NpLiquidation generated by HP
 */
 //******************
 // MODIFICATION HISTORY
 // Person          Date         Comments
 // ------------    ----------   -------------------------------------------
 // KCARPIOT        17-07-2014   RENIEC_IDDATA10: Se modifico reporte para agregar columnas de display:
 //                              nporderhour, npdocumenttype, npverificacion, npconexion
 //                              en BD : HORA, TIPDOCNUMBER, VERIFICACION,CONEXION
 // KCARPIOT        31-07-2014   PORTA: Se agrega campos de Descripcion
 //                              en BD:  ORIGENPORTA, ESTADOPORTA, CEDENTEPORTA
 // KCARPIOT        12-08-2014   DEPOSITO EN GARANTIA: Se agrega campo de Descripcion del 
 //                              Tipo de Depósito para Reporte de Liquidaciones
 
public class NpLiquidation implements java.io.Serializable {

    // Fields    
    private String nporderdate;
    private String nplocalidad;
    private String npretailer;
    private String npstore;
    private String nppromotor;
    private String nppromotername;
    private String npordernumber;
    private String npordertypename;
    private String npsolution;
    private String npcliente;
    private String npdocumentnumber;
    private String npproducto;
    private String npsku;
    private String npmodelo;
    private String npplantarif;
    private Float nppriceequip;
    private Float nppricekit;
    private String npimei;
    private String npsim;
    private String npnumberphone;
    private String npvoucher;
    private String nptypepay;
    private String npstatusorder;
    private String npstatuseval;
    private String npflagdepoguarantee;
    private String nptyperetailer;
    private String npdivision;
    private String npnrocontrato;
    private Long npcodclient;
    private String npnroguia;
    private String npskudepoguarantee;
    private Float npcostguarantee;
    private String npvoucherguarantee;
    private String npriesgofinanc;
    private String npcapaendeu;
    private String npcantequip;
    private String npsalezone;
    private String npdepartment;
    private String npprovince;
    private String npsupervisornextel;
    private String npsocionegocio;
    private String npdnipromotor;
    private String npmodalidad;
    //BEGIN KCARPIOT RENIEC_IDDATA10 17/07/2014
    private String nporderhour;
    private String npdocumenttype;    
    private String npverificacion;
    private String npconexion;
    private String npcustportvalue;
    private String npcustomerbusinness;
    //END KCARPIOT RENIEC_IDDATA10 17/07/2014
    //BEGIN KCARPIOT DEPOSITO EN GARANTIA - 12/08/2014
     private String nptypewarranty;
    //END KCARPIOT DEPOSITO EN GARANTIA - 12/08/2014 
    //datos de portabilidad
    
     //FBERNALES -- AGREGAMOS LOS CAMPOS DE PORTABILIDAD AL NUEVO REPORTE
      private String NpNumPorta;
      private String NpOrigenPorta;
      private String NpEstadoPorta;
      private String NpCedentePorta;
      private String NpMotivoRecPorta;
      private String NpMontoAdeudadoPorta;
      private String NpMonedaPorta;
      private String NpFecVecUlFactPorta;
      private String NpFecEjecucionPorta;
    
    //END KCARPIOT DEPOSITO EN GARANTIA - 12/08/2014 
    //datos de portabilidad
    private NpPortabilidad portabilidad ;
    
    //FBERNALES 26/01/2015 - TIPO DE OPERACION
    private String NpTypeOperation;
    
    
    
    // Constructors

    /** default constructor */
    public NpLiquidation() {
    }

    /** minimal constructor */
   /* public NpSubWarehouseDetail(Long npsubwarehousedetailid) {
        this.npsubwarehousedetailid = npsubwarehousedetailid;
    }*/

    /** full constructor */
    /* public NpSubWarehouseDetail(Long npsubwarehousedetailid,
                                NpProduct npProduct,
                                NpSubWarehouse npSubWarehouse,
                                NpWarehouse npWarehouse, String npimei,
                                String npsim, String npblocked,
                                String npcreatedby, Date npcreateddate,
                                String npmodifiedby, Date npmodifieddate,
                                String npstatus) {
        this.npsubwarehousedetailid = npsubwarehousedetailid;
        this.npProduct = npProduct;
        this.npSubWarehouse = npSubWarehouse;
        this.npWarehouse = npWarehouse;
        this.npimei = npimei;
        this.npsim = npsim;
        this.npblocked = npblocked;
        this.npcreatedby = npcreatedby;
        this.npcreateddate = npcreateddate;
        this.npmodifiedby = npmodifiedby;
        this.npmodifieddate = npmodifieddate;
        this.npstatus = npstatus;
    }*/

    // Property accessors

    public void setNporderdate(String nporderdate) {
        this.nporderdate = nporderdate;
    }

    public String getNporderdate() {
        return nporderdate;
    }

    public void setNplocalidad(String nplocalidad) {
        this.nplocalidad = nplocalidad;
    }

    public String getNplocalidad() {
        return nplocalidad;
    }

    public void setNpretailer(String npretailer) {
        this.npretailer = npretailer;
    }

    public String getNpretailer() {
        return npretailer;
    }

    public void setNpstore(String npstore) {
        this.npstore = npstore;
    }

    public String getNpstore() {
        return npstore;
    }

    public void setNppromotor(String nppromotor) {
        this.nppromotor = nppromotor;
    }

    public String getNppromotor() {
        return nppromotor;
    }

    public void setNpordernumber(String npordernumber) {
        this.npordernumber = npordernumber;
    }

    public String getNpordernumber() {
        return npordernumber;
    }

    public void setNpordertypename(String npordertypename) {
        this.npordertypename = npordertypename;
    }

    public String getNpordertypename() {
        return npordertypename;
    }

    public void setNpsolution(String npsolution) {
        this.npsolution = npsolution;
    }

    public String getNpsolution() {
        return npsolution;
    }

    public void setNpcliente(String npcliente) {
        this.npcliente = npcliente;
    }

    public String getNpcliente() {
        return npcliente;
    }

    public void setNpproducto(String npproducto) {
        this.npproducto = npproducto;
    }

    public String getNpproducto() {
        return npproducto;
    }

    public void setNpsku(String npsku) {
        this.npsku = npsku;
    }

    public String getNpsku() {
        return npsku;
    }

    public void setNpmodelo(String npmodelo) {
        this.npmodelo = npmodelo;
    }

    public String getNpmodelo() {
        return npmodelo;
    }

    public void setNpplantarif(String npplantarif) {
        this.npplantarif = npplantarif;
    }

    public String getNpplantarif() {
        return npplantarif;
    }

    public void setNppriceequip(Float nppriceequip) {
        this.nppriceequip = nppriceequip;
    }

    public Float getNppriceequip() {
        return nppriceequip;
    }

    public void setNppricekit(Float nppricekit) {
        this.nppricekit = nppricekit;
    }

    public Float getNppricekit() {
        return nppricekit;
    }

    public void setNpimei(String npimei) {
        this.npimei = npimei;
    }

    public String getNpimei() {
        return npimei;
    }

    public void setNpsim(String npsim) {
        this.npsim = npsim;
    }

    public String getNpsim() {
        return npsim;
    }

    public void setNpnumberphone(String npnumberphone) {
        this.npnumberphone = npnumberphone;
    }

    public String getNpnumberphone() {
        return npnumberphone;
    }

    public void setNpvoucher(String npvoucher) {
        this.npvoucher = npvoucher;
    }

    public String getNpvoucher() {
        return npvoucher;
    }

    public void setNptypepay(String nptypepay) {
        this.nptypepay = nptypepay;
    }

    public String getNptypepay() {
        return nptypepay;
    }

    public void setNpstatusorder(String npstatusorder) {
        this.npstatusorder = npstatusorder;
    }

    public String getNpstatusorder() {
        return npstatusorder;
    }

    public void setNpstatuseval(String npstatuseval) {
        this.npstatuseval = npstatuseval;
    }

    public String getNpstatuseval() {
        return npstatuseval;
    }

    public void setNpflagdepoguarantee(String npflagdepoguarantee) {
        this.npflagdepoguarantee = npflagdepoguarantee;
    }

    public String getNpflagdepoguarantee() {
        return npflagdepoguarantee;
    }

    public void setNptyperetailer(String nptyperetailer) {
        this.nptyperetailer = nptyperetailer;
    }

    public String getNptyperetailer() {
        return nptyperetailer;
    }

    public void setNpdivision(String npdivision) {
        this.npdivision = npdivision;
    }

    public String getNpdivision() {
        return npdivision;
    }

    public void setNpnrocontrato(String npnrocontrato) {
        this.npnrocontrato = npnrocontrato;
    }

    public String getNpnrocontrato() {
        return npnrocontrato;
    }

    public void setNpcodclient(Long npcodclient) {
        this.npcodclient = npcodclient;
    }

    public Long getNpcodclient() {
        return npcodclient;
    }

    public void setNpnroguia(String npnroguia) {
        this.npnroguia = npnroguia;
    }

    public String getNpnroguia() {
        return npnroguia;
    }

    public void setNpskudepoguarantee(String npskudepoguarantee) {
        this.npskudepoguarantee = npskudepoguarantee;
    }

    public String getNpskudepoguarantee() {
        return npskudepoguarantee;
    }

    public void setNpcostguarantee(Float npcostguarantee) {
        this.npcostguarantee = npcostguarantee;
    }

    public Float getNpcostguarantee() {
        return npcostguarantee;
    }

    public void setNpvoucherguarantee(String npvoucherguarantee) {
        this.npvoucherguarantee = npvoucherguarantee;
    }

    public String getNpvoucherguarantee() {
        return npvoucherguarantee;
    }

    public void setNpriesgofinanc(String npriesgofinanc) {
        this.npriesgofinanc = npriesgofinanc;
    }

    public String getNpriesgofinanc() {
        return npriesgofinanc;
    }

    public void setNpcapaendeu(String npcapaendeu) {
        this.npcapaendeu = npcapaendeu;
    }

    public String getNpcapaendeu() {
        return npcapaendeu;
    }

    public void setNpcantequip(String npcantequip) {
        this.npcantequip = npcantequip;
    }

    public String getNpcantequip() {
        return npcantequip;
    }

    public void setNpsalezone(String npsalezone) {
        this.npsalezone = npsalezone;
    }

    public String getNpsalezone() {
        return npsalezone;
    }

    public void setNppromotername(String nppromotername) {
        this.nppromotername = nppromotername;
    }

    public String getNppromotername() {
        return nppromotername;
    }

    public void setNpdocumentnumber(String npdocumentnumber) {
        this.npdocumentnumber = npdocumentnumber;
    }

    public String getNpdocumentnumber() {
        return npdocumentnumber;
    }

    public void setNpsocionegocio(String npsocionegocio) {
        this.npsocionegocio = npsocionegocio;
    }

    public String getNpsocionegocio() {
        return npsocionegocio;
    }

    public void setNpdnipromotor(String npdnipromotor) {
        this.npdnipromotor = npdnipromotor;
    }

    public String getNpdnipromotor() {
        return npdnipromotor;
    }

    public void setNpmodalidad(String npmodalidad) {
        this.npmodalidad = npmodalidad;
    }

    public String getNpmodalidad() {
        return npmodalidad;
    }

    public void setNpdepartment(String npdepartment) {
        this.npdepartment = npdepartment;
    }

    public String getNpdepartment() {
        return npdepartment;
    }

    public void setNpprovince(String npprovince) {
        this.npprovince = npprovince;
    }

    public String getNpprovince() {
        return npprovince;
    }

    public void setNpsupervisornextel(String npsupervisornextel) {
        this.npsupervisornextel = npsupervisornextel;
    }

    public String getNpsupervisornextel() {
        return npsupervisornextel;
    }

    //BEGIN KCARPIOT RENIEC_IDDATA10 17/07/2014
    //FBERNALES - YA NO SE NECESITA LA CLASE NpPortabilidad 22/10/2010
    public NpPortabilidad getPortabilidad() {
        return portabilidad;
    }

    public void setPortabilidad(NpPortabilidad portabilidad) {
        this.portabilidad = portabilidad;
    }
    
    public void setNporderhour(String nporderhour) {
        this.nporderhour = nporderhour;
    }

    public String getNporderhour() {
        return nporderhour;
    }

    public void setNpdocumenttype(String npdocumenttype) {
        this.npdocumenttype = npdocumenttype;
    }

    public String getNpdocumenttype() {
        return npdocumenttype;
    }

    public void setNpverificacion(String npverificacion) {
        this.npverificacion = npverificacion;
    }

    public String getNpverificacion() {
        return npverificacion;
    }

    public void setNpconexion(String npconexion) {
        this.npconexion = npconexion;
    }

    public String getNpconexion() {
        return npconexion;
    }
    
    public void setNptypewarranty(String nptypewarranty) {
        this.nptypewarranty = nptypewarranty;
    }
    
    public void setNpcustportvalue(String npcustportvalue) {
        this.npcustportvalue = npcustportvalue;
    }

    public String getNpcustportvalue() {
        return this.npcustportvalue;
    }

    public void setNpcustomerbusinness(String npcustomerbusinness) {
        this.npcustomerbusinness = npcustomerbusinness;
    }

    public String getNpcustomerbusinness() {
       return this.npcustomerbusinness;
    }

    public String getNptypewarranty() {
        return nptypewarranty;
    }
    //END KCARPIOT RENIEC_IDDATA10 17/07/2014

    public void setNpNumPorta(String npNumPorta) {
        this.NpNumPorta = npNumPorta;
    }

    public String getNpNumPorta() {
        return NpNumPorta;
    }

    public void setNpOrigenPorta(String npOrigenPorta) {
        this.NpOrigenPorta = npOrigenPorta;
    }

    public String getNpOrigenPorta() {
        return NpOrigenPorta;
    }

    public void setNpEstadoPorta(String npEstadoPorta) {
        this.NpEstadoPorta = npEstadoPorta;
    }

    public String getNpEstadoPorta() {
        return NpEstadoPorta;
    }

    public void setNpCedentePorta(String npCedentePorta) {
        this.NpCedentePorta = npCedentePorta;
    }

    public String getNpCedentePorta() {
        return NpCedentePorta;
    }

    public void setNpMotivoRecPorta(String npMotivoRecPorta) {
        this.NpMotivoRecPorta = npMotivoRecPorta;
    }

    public String getNpMotivoRecPorta() {
        return NpMotivoRecPorta;
    }

    public void setNpMontoAdeudadoPorta(String npMontoAdeudadoPorta) {
        this.NpMontoAdeudadoPorta = npMontoAdeudadoPorta;
    }

    public String getNpMontoAdeudadoPorta() {
        return NpMontoAdeudadoPorta;
    }

    public void setNpMonedaPorta(String npMonedaPorta) {
        this.NpMonedaPorta = npMonedaPorta;
    }

    public String getNpMonedaPorta() {
        return NpMonedaPorta;
    }

    public void setNpFecVecUlFactPorta(String npFecVecUlFactPorta) {
        this.NpFecVecUlFactPorta = npFecVecUlFactPorta;
    }

    public String getNpFecVecUlFactPorta() {
        return NpFecVecUlFactPorta;
    }

    public void setNpFecEjecucionPorta(String npFecEjecucionPorta) {
        this.NpFecEjecucionPorta = npFecEjecucionPorta;
    }

    public String getNpFecEjecucionPorta() {
        return NpFecEjecucionPorta;
    }

    public void setNpTypeOperation(String npTypeOperation) {
        this.NpTypeOperation = npTypeOperation;
    }

    public String getNpTypeOperation() {
        return NpTypeOperation;
    }
}
